import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1  >
          pay2win
        </h1>

        <p className={styles.description}  >
          Get easy money with pay 2 win.
         
        </p>
        <Link href="/example" >
          <a className="text-3xl font-bold underline bg-red-500 rounded p-4  mt-5 cursor-pointer inline-block hover:bg-red-400">link to example page</a>
        </Link>


    </div>
  )
}
